### PR TITLE
Add BuildAgent

### PR DESCRIPTION
**Pull request by kurtmc**
We are seeing 400s from artifactory when using this resource. It looks like artifactory is expecting a buildAgent property to be set now. Example exception:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at io.spring.((redacted)).artifactoryresource.Application.main(Application.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 : "{<EOL>  "errors" : [ {<EOL>    "status" : 400,<EOL>    "message" : "Cannot invoke \"org.jfrog.build.api.BuildAgent.toString()\" because the return value of \"org.jfrog.build.api.Build.getBuildAgent()\" is null"<EOL>  } ]<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:704)
	at io.spring.((redacted)).artifactoryresource.artifactory.HttpArtifactoryBuildRuns.add(HttpArtifactoryBuildRuns.java:95)
	at io.spring.((redacted)).artifactoryresource.artifactory.HttpArtifactoryBuildRuns.add(HttpArtifactoryBuildRuns.java:86)
	at io.spring.((redacted)).artifactoryresource.artifactory.ArtifactoryBuildRuns.add(ArtifactoryBuildRuns.java:48)
	at io.spring.((redacted)).artifactoryresource.command.OutHandler.addBuildRun(OutHandler.java:308)
	at io.spring.((redacted)).artifactoryresource.command.OutHandler.handle(OutHandler.java:135)
	at io.spring.((redacted)).artifactoryresource.command.OutCommand.run(OutCommand.java:58)
	at io.spring.((redacted)).artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:56)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
	... 13 common frames omitted
```

### CODE REVIEW

**Comment by philwebb** [comment]
What version of Artifactory are you using?

**Comment by kurtmc** [comment]
@philwebb We are using the cloud offering from Jfrog.

**Comment by wilkinsona** [comment]
Curiously, the integration tests pass when updated to use Artifactory 7.9.2. Those tests do add a build run.

@kurtmc Can you tell which version of Artifactory your cloud instance is using? FWIW, https://repo.spring.io is a JFrog Cloud instance and it is not affected by the problem that you're seeing.

**Comment by kurtmc** [comment]
This is what I get from the `/artifactory/api/system/version` endpoint:
```
{
  "version" : "7.68.6",
  "revision" : "76806900",
  "addons" : [ "aol", "ha", "build", "docker", "helmoci", "oci", "packages-archive", "vagrant", "replication", "filestore", "curation", "plugins", "worker", "gems", "composer", "npm", "bower", "git-lfs", "nuget", "debian", "opkg", "rpm", "cocoapods", "conan", "vcs", "pypi", "release-bundle", "jf-connect", "jf-event", "replicator", "keys", "alpine", "analytics", "cargo", "chef", "federated", "git", "observability", "onboarding", "pub", "rest", "swift", "conda", "terraform", "tracker", "license", "puppet", "ldap", "sso", "layouts", "properties", "search", "securityresourceaddon", "filtered-resources", "p2", "watch", "webstart", "support", "xray", "retention" ],
  "license" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "entitlements" : {
    "EVENT_BASED_PULL_REPLICATION" : true,
    "SMART_REMOTE_TARGET_FOR_EDGE" : false,
    "REPO_REPLICATION" : true,
    "MULTIPUSH_REPLICATION" : true
  }
}
```

**Comment by wilkinsona** [comment]
Thanks. That 7.68.x version number made me realise I'd done a poor job of scanning [the list of `artifactory-oss`](https://releases-docker.jfrog.io/ui/repos/tree/General/docker/jfrog/artifactory-oss) tags. 7.63.14 is actually the latest version at the time of writing. Unfortunately, running the integration tests against that version doesn't reproduce the failure either.

repo.spring.io appears to be a slightly newer version:

```
$ http https://repo.spring.io/artifactory/api/system/version | jq .version 
"7.68.7"
```

I wonder if the failure you're seeing is a bug in the earlier 7.68.x releases that was fixed in 7.68.7?

**Comment by kurtmc** [comment]
So I checked today and I see we are on `7.68.7` now, so I decided to rerun the job with the latest release of this resource (18) and with debug logs turned on we get:

```
2023-09-08T21:48:16.764Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Generated build number 2023-09-08.214816763959718
2023-09-08T21:48:16.765Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Using artifactory server https://xxxxxxxxxxxxxxxxxxxxxx
2023-09-08T21:48:17.463Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Getting deployable artifacts from /tmp/build/put/jar
2023-09-08T21:48:17.474Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Including file /tmp/build/put/jar/io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.jar with path /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.jar
2023-09-08T21:48:17.474Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Creating artifact set filter including [/**/*.pom, /**/*.jar] and excluding []
2023-09-08T21:48:17.475Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Artifact set matched, adding properties {}
2023-09-08T21:48:17.478Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Including file /tmp/build/put/jar/io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.pom with path /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.pom
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Creating artifact set filter including [/**/*.pom, /**/*.jar] and excluding []
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Artifact set matched, adding properties {}
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Including file /tmp/build/put/jar/io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-javadoc.jar with path /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-javadoc.jar
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Creating artifact set filter including [/**/*.pom, /**/*.jar] and excluding []
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Artifact set matched, adding properties {}
2023-09-08T21:48:17.479Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Including file /tmp/build/put/jar/io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-sources.jar with path /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-sources.jar
2023-09-08T21:48:17.480Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Creating artifact set filter including [/**/*.pom, /**/*.jar] and excluding []
2023-09-08T21:48:17.480Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Artifact set matched, adding properties {}
Deploying 4 artifacts to https://xxxxxx.jfrog.io/xxxxxx as build 2023-09-08.214816763959718 using 1 thread(s)
2023-09-08T21:48:17.481Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Deploying artifacts to maven
2023-09-08T21:48:17.483Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Deploying pimary artifacts
Deploying /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.jar {build.name=xxxxxxxxxxxxxxxxx, build.number=2023-09-08.214816763959718, build.timestamp=1694209696765} (20791e48068eb33ed2c4db769a7bd54bce092415/1ce0e323571175429861edc048eecf52)
2023-09-08T21:48:17.876Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Deploying pom file artifacts
Deploying /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory.pom {build.name=xxxxxxxxxxxxxxxxx, build.number=2023-09-08.214816763959718, build.timestamp=1694209696765} (a34d57bfc923f5b4aebff636f1730e83c96f3f96/ff5a8370eed06baffc11f7a9a02bd064)
2023-09-08T21:48:18.087Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Deploying additional artifacts
Deploying /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-sources.jar {build.name=xxxxxxxxxxxxxxxxx, build.number=2023-09-08.214816763959718, build.timestamp=1694209696765} (501c78eb600de4bcd6871fd41ab90d69f2e3f5f5/bee4207d9a58191197dd465495c732a2)
Deploying /io/xxxxxx/client/xxxxxxxxxxxxxxxxx/artifactory/xxxxxxxxxxxxxxxxx-artifactory-javadoc.jar {build.name=xxxxxxxxxxxxxxxxx, build.number=2023-09-08.214816763959718, build.timestamp=1694209696765} (e7d21d38e432383809e9cab767f13f0ad986eddc/ccfa244586b9a3a24e66b43d61e0173a)
2023-09-08T21:48:18.556Z DEBUG 11 --- [           main] i.s.c.a.command.OutHandler               : Adding build run 2023-09-08.214816763959718
2023-09-08T21:48:18.560Z DEBUG 11 --- [           main] i.s.c.a.a.HttpArtifactoryBuildRuns       : Adding 2023-09-08.214816763959718 from CI agent null
2023-09-08T21:48:18.800Z  INFO 11 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-09-08T21:48:18.816Z ERROR 11 --- [           main] o.s.boot.SpringApplication               : Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291)
	at io.spring.artifactory.artifactoryresource.Application.main(Application.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 : "{<EOL>  "errors" : [ {<EOL>    "status" : 400,<EOL>    "message" : "Cannot invoke \"org.jfrog.build.api.BuildAgent.toString()\" because the return value of \"org.jfrog.build.api.Build.getBuildAgent()\" is null"<EOL>  } ]<EOL>}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:183)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:137)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:915)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:864)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:704)
	at io.spring.artifactory.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.add(HttpArtifactoryBuildRuns.java:95)
	at io.spring.artifactory.artifactoryresource.artifactory.HttpArtifactoryBuildRuns.add(HttpArtifactoryBuildRuns.java:86)
	at io.spring.artifactory.artifactoryresource.artifactory.ArtifactoryBuildRuns.add(ArtifactoryBuildRuns.java:48)
	at io.spring.artifactory.artifactoryresource.command.OutHandler.addBuildRun(OutHandler.java:308)
	at io.spring.artifactory.artifactoryresource.command.OutHandler.handle(OutHandler.java:135)
	at io.spring.artifactory.artifactoryresource.command.OutCommand.run(OutCommand.java:58)
	at io.spring.artifactory.artifactoryresource.command.CommandProcessor.run(CommandProcessor.java:56)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
	... 13 common frames omitted
```

**Comment by prafsoni-smarsh** [comment]
We also started to see this issue. Is there a workaround while we wait for the fix?

**Comment by wilkinsona** [comment]
Not that we're aware of, I'm afraid.

@prafsoni-smarsh Can you please provide as much info as possible about your Artifactory environment? We've been unable to reproduce the problem which makes it hard to assess and verify the proposed fix.

**Comment by prafsoni-smarsh** [comment]
@wilkinsona  Here's the output from the `/artifactory/api/system/version` endpoint:

```json
{
    "addons": [
        "aol", "ha", "build", "docker", "helmoci", "oci", "packages-archive", "vagrant", "replication", "filestore", "curation", "plugins", "worker", "gems", "composer", "npm", "bower", "git-lfs", "nuget", "debian", "opkg", "rpm", "cocoapods", "conan", "vcs", "pypi", "release-bundle", "jf-connect", "jf-event", "replicator", "keys", "alpine", "analytics", "cargo", "chef", "federated", "git", "observability", "onboarding", "pub", "rest", "swift", "lead-artifact-detector", "conda", "terraform", "tracker", "license", "puppet", "ldap", "sso", "layouts", "properties", "search", "securityresourceaddon", "filtered-resources", "p2", "watch", "webstart", "support", "xray", "retention"
    ],
    "entitlements": {
        "EVENT_BASED_PULL_REPLICATION": true,
        "MULTIPUSH_REPLICATION": true,
        "REPO_REPLICATION": true,
        "SMART_REMOTE_TARGET_FOR_EDGE": false
    },
    "license": "xxxxxxxxxxxxxxxx",
    "revision": "76904900",
    "version": "7.69.4"
}
```

**Comment by prafsoni-smarsh** [comment]
@wilkinsona is there a way to get a snapshot ? from this PR that I could test and validate it in our env?

**Comment by philwebb** [comment]
@prafsoni-smarsh The only way would be to checkout the PR branch and build it locally

**Comment by kurtmc** [comment]
@prafsoni-smarsh I've built this into a container that we are using while we wait for this issue to be fixed, it's working well for us.

You can use `halternz/artifactory-resource`

**Comment by prafsoni-smarsh** [comment]
@kurtmc  Thanks we just completed local build and validation in pipelines and the fix appears to working as expected. Though I am curious if this is a satisfactory bug or new expected behavior can't seem to find anything in release notes and such. If you have additional info on that I would much appreciate it if you could post it here.

**Comment by kurtmc** [comment]
I don't really have any other information, this issue affected multiple pipelines so we just looked into it and noticed that we could add this build agent field to resolve the issue.

I'm glad you were able to confirm that it was not just happening to us!

**Comment by wilkinsona** [comment]
We've recently started using this resource to deploy to a new Artifactory instance that, like start.spring.io, is hosted on JFrog's cloud. For the purposes of this PR, I was hoping that it wouldn't work and that we'd see a failure when deploying the build info. Unfortunately, it worked fine. That leaves me still wondering what the difference might be.

@kurtmc, @prafsoni-smarsh can you please share some details about the build info configuration in your Artifactory instances? I'm wondering if there's a setting in there somewhere that may trigger the problem.

**Comment by wilkinsona** [comment]
The [Artifactory REST API documentation](https://jfrog.com/help/r/jfrog-rest-apis/build-upload) shows the `buildAgent` as optional:

> ```
> {
>   "properties" : {
>    /* Environment variables and properties collected from the CI server.
>       The "buildInfo.env." prefix is added to environment variables and build related properties.
>       For system variables there's no prefix. */
>    "buildInfo.env.JAVA_HOME" : "",
>    ...
>   },
> +  "version" : "1.0.1", // Build Info schema version
> +  "name" : "My-build-name", // Build name
> +  "number" : "28", // Build number
> -  "type" : "MAVEN", // Build type (values currently supported: MAVEN, GRADLE, ANT, IVY and GENERIC)
> -  "buildAgent" : { // Build tool information
> -    "name" : "Maven", // Build tool type
> -    "version" : "3.0.5" // Build tool version
>   },
> - "agent" : { // CI Server information
> -   "name" : "Jenkins", // CI server type
> -   "version" : "1.554.2" // CI server version
>    },
> +  "started" : "2014-09-30T12:00:19.893+0300", // Build start time in the format of yyyy-MM-dd'T'HH:mm:ss.SSSZ
> -  "artifactoryPluginVersion" : "2.3.1",
> -  "durationMillis" : 9762, // Build duration in milliseconds
> -  "artifactoryPrincipal" : "james", // Artifactory principal (the Artifactory user used for deployment)
> -  "url" : "http://my-ci-server/jenkins/job/My-project-name/28/", // CI server URL
> -  "vcsRevision" : "e4ab2e493afd369ae7bdc90d69c912e8346a3463", // VCS revision
> -  "vcsUrl" : "https://github.com/github-user/my-project.git", // VCS URL
> -  "licenseControl" : {  // Artifactory License Control information
> -   "runChecks" : true, // Artifactory will run automatic license scanning after the build is complete (true/false)
> -   "includePublishedArtifacts" : true, // Should Artifactory run license checks on the build artifacts, in addition to the build dependecies (true/false) 
> -   "autoDiscover" : true, // Should Artifactory auto discover licenses (true/false)
> -   "scopesList" : "", // A space-separated list of dependency scopes/configurations to run license violation checks on. If left empty all dependencies from all scopes will be checked.
> -   "licenseViolationsRecipientsList" : "" // Emails of recipients that should be notified of license violations in the build info (space-separated list)
>   },
> -  "buildRetention" : { // Build retention information
> -  "deleteBuildArtifacts" : true, // Automatically remove build artifacts stored in Artifactory (true/false)
> -   "count" : 100, // The maximum number of builds to store in Artifactory.
> -   "minimumBuildDate" : 1407345768020, // Earliest build date to store in Artifactory
> -   "buildNumbersNotToBeDiscarded" : [ ] // List of build numbers that should not be removed from Artifactory
>   },
>   /* List of build modules */   
> -  "modules" : [ { // The build's first module
> -    "properties" : { // Module properties
> -      "project.build.sourceEncoding" : "UTF-8"
>     },
> -   "id" : "org.jfrog.test:multi2:4.2-SNAPSHOT", // Module ID
> -   /* List of module artifacts */
>     "artifacts" : [ {
> -     "type" : "jar",
> -     "sha1" : "2ed52ad1d864aec00d7a2394e99b3abca6d16639",
> -     "md5" : "844920070d81271b69579e17ddc6715c",
> -     "name" : "multi2-4.2-SNAPSHOT.jar"
>     }, {
> -     "type" : "pom",
> -     "sha1" : "e8e9c7d790191f4a3df3a82314ac590f45c86e31",
> -     "md5" : "1f027d857ff522286a82107be9e807cd",
> -     "name" : "multi2-4.2-SNAPSHOT.pom"
>     } ],
>     /* List of module dependencies */
>     "dependencies" : [ {
> -    "type" : "jar",
> -    "sha1" : "99129f16442844f6a4a11ae22fbbee40b14d774f",
> -    "md5" : "1f40fb782a4f2cf78f161d32670f7a3a",
> -    "id" : "junit:junit:3.8.1",
> -    "scopes" : [ "test" ]
>     } ]
>   }, { // The build's second module
>     "properties" : { // Module properties
>       "project.build.sourceEncoding" : "UTF-8"
>     },
>     "id" : "org.jfrog.test:multi3:4.2-SNAPSHOT", // Module ID
>     /* List of module artifacts */  
>     "artifacts" : [ { // Module artifacts
> -     "type" : "war",
> -     "sha1" : "df8e7d7b94d5ec9db3bfc92e945c7ff4e2391c7c",
> -     "md5" : "423c24f4c6e259f2774921b9d874a649",
> -     "name" : "multi3-4.2-SNAPSHOT.war"
>     }, {
> -     "type" : "pom",
> -     "sha1" : "656330c5045130f214f954643fdc4b677f4cf7aa",
> -     "md5" : "b0afa67a9089b6f71b3c39043b18b2fc",
> -     "name" : "multi3-4.2-SNAPSHOT.pom"
>    } ],
>     /* List of module dependencies */
>     "dependencies" : [ {
> -     "type" : "jar",
> -    "sha1" : "a8762d07e76cfde2395257a5da47ba7c1dbd3dce",
> -     "md5" : "b6a50c8a15ece8753e37cbe5700bf84f",
> -    "id" : "commons-io:commons-io:1.4",
> -     "scopes" : [ "compile" ]
>     }, {
> -     "type" : "jar",
> -     "sha1" : "342d1eb41a2bc7b52fa2e54e9872463fc86e2650",
> -     "md5" : "2a666534a425add50d017d4aa06a6fca",
> -     "id" : "org.codehaus.plexus:plexus-utils:1.5.1",
>       "scopes" : [ "compile" ]
>     }, {
> -     "type" : "jar",
> -     "sha1" : "449ea46b27426eb846611a90b2fb8b4dcf271191",
> -     "md5" : "25c0752852205167af8f31a1eb019975",
> -     "id" : "org.springframework:spring-beans:2.5.6",
> -     mandma"scopes" : [ "compile" ]
>     } ]
>   } ],
>   /* List of issues related to the build */
>     "issues" : {
>     "tracker" : {
> -     "name" : "JIRA",
> -     "version" : "6.0.1"
>     },
> -  "aggregateBuildIssues" : true,  //whether or not there are issues that already appeared in previous builds
> -   "aggregationBuildStatus" : "Released",
>     "affectedIssues" : [ {
> -     "key" : "RTFACT-1234",
> -      "url" : "https://www.jfrog.com/jira/browse/RTFACT-1234",
> -      "summary" : "Description of the relevant issue",
> -      "aggregated" : false  //whether or not this specific issue already appeared in previous builds
>     }, {
> -     "key" : "RTFACT-5469",
> -     "url" : "https://www.jfrog.com/jira/browse/RTFACT-5678",
> -     "summary" : "Description of the relevant issue",
> -     "aggregated" : true
>     } ] 
>    },  
>   }
> }
> ```
> 
> +=mandatory; -=optional

It also shows that it should be information about the build tool, not the CI system:

```
"buildAgent" : { // Build tool information
    "name" : "Maven", // Build tool type
    "version" : "3.0.5" // Build tool version
},
```

Given that it's documented as optional and that it should be build tool information, I don't think we should hardcode sending information about the CI system. If you're seeing an upload rejected without `buildAgent`, I would raise it with JFrog as the server's behaviour does not match the documentation.

We could consider input parameters to the resource that allow the name and version of the build tool to be passed in but I think that should be tracked as a separate issue/PR.

Thanks anyway for the suggestion.

**Comment by wilkinsona** [comment]
Those who were interested in this PR, I have just pushed a somewhat similar change to address https://github.com/spring-io/artifactory-resource/issues/121. The `buildAgent` is now hardcoded to describe this resource. This is in line with what JFrog's own CLI does.

**Pull request closed without merging**
